spring.application.name=gatewaybatch5

server:8082

eureka.client.serviceurl.defaultzone=http://localhost:9000/eureka

# Producer Service Route
spring.cloud.gateway.route[0].id=banking
spring.cloud.gateway.route[0].uri=http://localhost;10000
spring.cloud.gateway.route[0].predicates[0]=Path=/api/v1/employees/**

